// The logo inside the app, drawn from the same geometry as branding/ (src/ui/brandMarks.ts is
// generated by scripts/make-logo.mjs). Colours come from the theme: navy body on cream, cream
// body on navy, mint flap in both.

import { MARK, WORDMARK } from './brandMarks';

export function Wordmark({ title = 'Where It All Is' }: { title?: string }) {
  return (
    <svg class="wordmark" viewBox={WORDMARK.viewBox} role="img" aria-label={title}>
      <g transform={WORDMARK.markTransform}>
        <path class="wm-flap" d={MARK.flap} />
        <path class="wm-body" d={MARK.body} />
      </g>
      <path class="wm-text" d={WORDMARK.text} />
    </svg>
  );
}

export function BrandMark({ size }: { size: 'sm' | 'lg' }) {
  return (
    <svg class={`brand-mark brand-mark-${size}`} viewBox={MARK.viewBox} aria-hidden="true" focusable="false">
      <path class="wm-flap" d={MARK.flap} />
      <path class="wm-body" d={MARK.body} />
    </svg>
  );
}
