// Builds site/ for Cloudflare Pages:
//   /                 landing page (links only to the demo and the Etsy listing)
//   /demo/            demo build (PWA, offline after the first visit)
//   /<appPath>/       full app (PWA, offline) — private path from site.config.json, never linked publicly
// Run: npm run build:site
import { execSync } from 'node:child_process';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

const cfg = JSON.parse(fs.readFileSync('site.config.json', 'utf8'));
const OUT = 'site';
const TMP = '.site-build';
const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]);

if (!/^app-[a-z0-9]{12}$/.test(cfg.appPath)) throw new Error(`site.config.json appPath must look like "app-" + 12 characters, got "${cfg.appPath}"`);

execSync('node scripts/make-icons.mjs', { stdio: 'inherit' });

// 1. The two hosted builds (single-file pages with manifest + service worker registration).
fs.rmSync(TMP, { recursive: true, force: true });
for (const [mode, dir] of [['app', 'app'], ['demo', 'demo']]) {
  execSync(`npx vite build --mode ${mode} --logLevel warn`, {
    stdio: 'inherit',
    env: { ...process.env, HOSTED: '1', OUT_DIR: path.join(TMP, dir), OUT_NAME: 'index.html' },
  });
}

// 2. Assemble site/.
fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

function pwaDir(dir, srcHtml, { name, shortName }) {
  const target = path.join(OUT, dir);
  fs.mkdirSync(path.join(target, 'icons'), { recursive: true });
  fs.copyFileSync(srcHtml, path.join(target, 'index.html'));
  fs.copyFileSync(cfg.icons.icon192, path.join(target, 'icons/icon-192.png'));
  fs.copyFileSync(cfg.icons.icon512, path.join(target, 'icons/icon-512.png'));
  fs.copyFileSync(cfg.icons.maskable512, path.join(target, 'icons/icon-maskable-512.png'));
  const manifest = {
    name,
    short_name: shortName,
    description: 'A calm budget planner that tells you what’s safe to spend today. Works offline; your data stays on your device.',
    start_url: './',
    scope: './',
    display: 'standalone',
    orientation: 'portrait',
    background_color: cfg.backgroundColor,
    theme_color: cfg.themeColor,
    icons: [
      { src: 'icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: 'icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: 'icons/icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  };
  fs.writeFileSync(path.join(target, 'manifest.webmanifest'), JSON.stringify(manifest, null, 2));
  const files = ['index.html', 'manifest.webmanifest', 'icons/icon-192.png', 'icons/icon-512.png', 'icons/icon-maskable-512.png'];
  const hash = crypto.createHash('sha256');
  for (const f of files) hash.update(fs.readFileSync(path.join(target, f)));
  const version = hash.digest('hex').slice(0, 12);
  fs.writeFileSync(path.join(target, 'sw.js'), serviceWorker(dir === 'demo' ? 'demo' : 'app', version, files));
  return version;
}

function serviceWorker(scopeName, version, files) {
  return `// Offline support for ${cfg.productName} (${scopeName}). Generated by scripts/build-site.mjs.
// Cache-first: after the first visit the app opens with no connection. A new version is fetched
// in the background and used next time the app opens.
const CACHE = 'wiai-${scopeName}-${version}';
const FILES = ${JSON.stringify(files.map((f) => './' + f))};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('wiai-${scopeName}-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  const url = new URL(req.url);
  if (req.method !== 'GET' || url.origin !== self.location.origin || !url.href.startsWith(self.registration.scope)) return;
  const key = req.mode === 'navigate' ? new URL('./index.html', self.registration.scope).href : req;
  event.respondWith(
    caches.open(CACHE).then(async (cache) => {
      const hit = await cache.match(key, { ignoreSearch: true });
      const fresh = fetch(req)
        .then((res) => {
          if (res.ok && res.type === 'basic') cache.put(key, res.clone());
          return res;
        })
        .catch(() => hit);
      return hit || fresh;
    }),
  );
});
`;
}

const appVersion = pwaDir(cfg.appPath, path.join(TMP, 'app/index.html'), { name: cfg.productName, shortName: cfg.shortName });
const demoVersion = pwaDir('demo', path.join(TMP, 'demo/index.html'), { name: `${cfg.productName} — Demo`, shortName: 'Budget demo' });

// 3. Landing page: links to the demo and the Etsy listing only. Never the app path.
fs.mkdirSync(path.join(OUT, 'icons'), { recursive: true });
fs.copyFileSync(cfg.icons.icon192, path.join(OUT, 'icons/icon-192.png'));
fs.writeFileSync(path.join(OUT, 'index.html'), landingPage());
fs.writeFileSync(path.join(OUT, 'robots.txt'), 'User-agent: *\nAllow: /\n');
// Cloudflare Pages reads _headers (it isn't served as a file).
fs.writeFileSync(
  path.join(OUT, '_headers'),
  [
    '/*',
    '  X-Content-Type-Options: nosniff',
    '  Referrer-Policy: no-referrer',
    '  Permissions-Policy: camera=(), microphone=(), geolocation=(), interest-cohort=()',
    '  X-Frame-Options: DENY',
    '',
    '/*/sw.js',
    '  Cache-Control: no-cache',
    '',
    `/${cfg.appPath}/*`,
    '  X-Robots-Tag: noindex, nofollow',
    '',
  ].join('\n'),
);

function landingPage() {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src 'self'; base-uri 'none'; form-action 'none'" />
<title>${esc(cfg.productName)} — a calm budget planner</title>
<meta name="description" content="A calm, offline budget planner that tells you what’s safe to spend today. ADHD-friendly design. No account, no bank login — your data stays on your device." />
<link rel="icon" type="image/png" href="icons/icon-192.png" />
<style>
  :root { color-scheme: light dark; --bg:#f6f4ef; --text:#1f2430; --muted:#5a6070; --accent:#2f6f62; --accent-text:#fff; --card:#fff; --border:#dcd8ce; }
  @media (prefers-color-scheme: dark) { :root { --bg:#11151d; --text:#e9ebf1; --muted:#a6adbd; --accent:#7cc7b5; --accent-text:#0d1a17; --card:#1a202b; --border:#2f3746; } }
  * { box-sizing: border-box; }
  body { margin:0; background:var(--bg); color:var(--text); font: 18px/1.5 system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif; }
  main { max-width: 640px; margin: 0 auto; padding: 48px 20px; }
  img { width: 72px; height: 72px; border-radius: 18px; }
  h1 { font-size: 34px; margin: 16px 0 8px; letter-spacing: -0.01em; }
  .lead { font-size: 20px; margin: 0 0 24px; }
  ul { padding-left: 1.2em; color: var(--muted); }
  li { margin: 6px 0; }
  .actions { display: grid; gap: 12px; margin: 28px 0; }
  a.btn { display: flex; align-items: center; justify-content: center; min-height: 52px; border-radius: 14px; font-weight: 700; text-decoration: none; }
  a.primary { background: var(--accent); color: var(--accent-text); }
  a.secondary { border: 1px solid var(--border); background: var(--card); color: var(--text); }
  footer { font-size: 14px; color: var(--muted); margin-top: 40px; }
  a:focus-visible { outline: 3px solid #1d5fd1; outline-offset: 2px; }
</style>
</head>
<body>
<main>
  <img src="icons/icon-192.png" alt="" />
  <h1>${esc(cfg.productName)}</h1>
  <p class="lead">A calm budget planner that answers one question: how much is safe to spend today?</p>
  <ul>
    <li>No account, no bank login, no subscription.</li>
    <li>Works offline. Your numbers stay on your device.</li>
    <li>Import your bank’s CSV statement instead of typing everything.</li>
  </ul>
  <div class="actions">
    <a class="btn primary" href="demo/">Try the free demo</a>
    <a class="btn secondary" href="${esc(cfg.etsyUrl)}" rel="noopener">Get the full version on Etsy</a>
  </div>
  <footer>A budgeting and organising tool. Not financial advice. ADHD-friendly design; not a medical product.</footer>
</main>
</body>
</html>
`;
}

// 4. Safety check: the private app path must not appear anywhere public.
for (const f of ['index.html', 'robots.txt', 'demo/index.html', 'demo/manifest.webmanifest', 'demo/sw.js']) {
  if (fs.readFileSync(path.join(OUT, f), 'utf8').includes(cfg.appPath)) throw new Error(`The private app path leaked into ${f}`);
}
fs.rmSync(TMP, { recursive: true, force: true });

console.log(`\nsite/ ready for Cloudflare Pages:
  /                  landing (links to /demo/ and Etsy only)
  /demo/             demo        (sw ${demoVersion})
  /${cfg.appPath}/  full app    (sw ${appVersion})  ← private: give customers ${cfg.siteUrl}/${cfg.appPath}/`);
